
---
spring:
  jpa:
    generate-ddl: true
security:
 basic:
  oauth2:
   client:
    client-id: e0f8eb4d-b92d-4049-9dcc-d13e26583a5d
    client-secret: e0f8eb4d-b92d-4049-9dcc-d13e26583a5d
   resource: token-info-uri=http://localhost:8080/oauth/check_token
server:
 port: 8095
